mysql:
  host: mkblog-db     # 数据库地址
  port: 3306          # 数据库端口
  user: mkblog        # 数据库用户
  password: mkblog    # 数据库密码
  name: mkblog        # 数据库名称

tls:
  enabled: false              # 是否启用TLS
  cert: ./static/server.crt   # TLS证书文件路径
  key: ./static/server.key    # TLS密钥文件路径

auth:
  enabled: true                         # 是否启用身份验证
  secret: "123456789015234564892545456" # 自行设置验证密码

server:
  port: 8080                     # 服务器端口
  imageSavePath: ./static/images # 图片保存路径
  limiter:
    requests: 100                # 每个IP在duration内最多允许的请求数
    duration: 5                  # 限制的时间窗口，单位为秒
  devmode: true

site:
  signature: "鼠鼠是穿越者..."      # 个性签名
  about: "鼠鼠是一个喜欢折腾的程序员..." # 关于我
  avatarPath: avatar.jpg          # 头像路径
  server: http://localhost:8080   # 服务器地址(端口为80/443时后面不需要加端口号)
  devmode: true                   # 开发模式，启用后前端使用未压缩的资源文件
  comment_enabled: true           # 是否启用评论功能
  icp: 粤ICP备123456789号        # 备案号（可选）